#!/usr/bin/env python3
"""Render Omarski's original sprite set.

Every sprite in assets/sprites/ is generated from the pixel grids and drawing
code in this file. The artwork is original to this project (drawn for Omarski,
in a 16-colour early-90s style) and is licensed with the rest of the plugin,
so the whole repository is freely redistributable.

The catalog ids and canvas sizes match game/Sprites.js, which the engine uses
for layout and collision. Only Python's standard library is required:

    python3 tools/make-sprites.py [-o OUTDIR]
"""

import argparse
import os
import struct
import sys
import zlib

# ---------------------------------------------------------------------------
# Palette
# ---------------------------------------------------------------------------
# One character per colour. '.' (and ' ') are transparent.

PALETTE = {
    "k": (0, 0, 0, 255),        # black
    "d": (85, 85, 85, 255),     # dark grey
    "g": (156, 156, 156, 255),  # grey
    "s": (207, 207, 207, 255),  # light grey
    "w": (255, 255, 255, 255),  # white
    "r": (208, 32, 32, 255),    # red
    "R": (143, 16, 16, 255),    # dark red
    "o": (240, 128, 32, 255),   # orange
    "y": (240, 208, 32, 255),   # yellow
    "e": (32, 160, 64, 255),    # green
    "E": (16, 96, 40, 255),     # dark green
    "t": (32, 160, 160, 255),   # teal
    "T": (16, 104, 104, 255),   # dark teal
    "b": (48, 96, 216, 255),    # blue
    "n": (16, 40, 112, 255),    # navy
    "p": (160, 64, 192, 255),   # purple
    "B": (122, 74, 32, 255),    # brown
    "L": (192, 138, 80, 255),   # tan
    "f": (240, 200, 160, 255),  # skin
    "m": (224, 112, 160, 255),  # pink (mouths, tongues)
}

# Sprite canvas sizes, kept identical to game/Sprites.js so the engine's
# layout and collision maths are untouched.
SIZES = {
    1: (16, 32), 2: (16, 32), 3: (24, 28), 4: (24, 28), 5: (16, 32),
    6: (24, 28), 7: (24, 28), 8: (24, 28), 9: (24, 28), 10: (24, 28),
    11: (24, 28), 12: (32, 32), 13: (32, 24), 14: (32, 32), 15: (28, 31),
    16: (28, 31), 17: (28, 34), 18: (32, 26), 19: (32, 32), 20: (31, 24),
    21: (25, 31), 22: (25, 31), 23: (12, 24), 24: (12, 24), 25: (12, 24),
    26: (12, 24), 27: (64, 32), 28: (24, 30), 29: (22, 29), 30: (21, 29),
    31: (24, 24), 32: (24, 24), 33: (21, 15), 34: (21, 15), 35: (19, 19),
    36: (19, 19), 37: (26, 30), 38: (20, 30), 39: (25, 31), 40: (30, 29),
    41: (32, 32), 42: (32, 32), 43: (25, 29), 44: (29, 25), 45: (23, 11),
    46: (16, 11), 47: (16, 4), 48: (24, 8), 49: (28, 32), 50: (22, 27),
    51: (32, 64), 52: (32, 8), 53: (93, 57), 54: (52, 10), 55: (92, 30),
    56: (63, 32), 57: (42, 27), 58: (42, 27), 59: (50, 29), 60: (50, 29),
    61: (40, 36), 62: (44, 36), 63: (40, 35), 64: (24, 64), 65: (26, 32),
    66: (26, 32), 67: (26, 32), 68: (32, 48), 69: (32, 48), 70: (32, 48),
    71: (32, 48), 72: (32, 48), 73: (32, 48), 74: (32, 48), 75: (32, 48),
    76: (32, 48), 77: (32, 48), 78: (32, 48), 79: (32, 48), 80: (32, 48),
    81: (32, 48), 82: (16, 8), 83: (22, 27), 84: (22, 27), 85: (22, 27),
    86: (8, 11), 87: (28, 32), 88: (28, 32), 89: (28, 32),
}

# ---------------------------------------------------------------------------
# Canvas helpers
# ---------------------------------------------------------------------------


def canvas(w, h, fill="."):
    return [[fill] * w for _ in range(h)]


def grid(text):
    """Parse a multi-line pixel grid, padding rows to the widest line."""
    lines = [ln for ln in text.splitlines() if ln.strip("") != ""]
    lines = [ln for ln in lines if ln != ""]
    width = max(len(ln) for ln in lines)
    return [list(ln.ljust(width, ".")) for ln in lines]


def mirror(rows):
    return [list(reversed(r)) for r in rows]


def shift_up(rows, n=1):
    """Move art up n rows inside the same canvas (a hop/bob frame)."""
    blank = [["."] * len(rows[0]) for _ in range(n)]
    return rows[n:] + blank


def remap(rows, table):
    return [[table.get(c, c) for c in r] for r in rows]


def blit(dst, src, x, y):
    for j, row in enumerate(src):
        for i, c in enumerate(row):
            if c in (".", " "):
                continue
            px, py = x + i, y + j
            if 0 <= px < len(dst[0]) and 0 <= py < len(dst):
                dst[py][px] = c
    return dst


def place(art, w, h, anchor="bottom"):
    """Centre `art` horizontally on a w x h canvas, bottom- or centre-anchored."""
    rows = grid(art) if isinstance(art, str) else art
    aw, ah = len(rows[0]), len(rows)
    if aw > w or ah > h:
        raise ValueError("art %dx%d exceeds canvas %dx%d" % (aw, ah, w, h))
    x = (w - aw) // 2
    y = (h - ah) if anchor == "bottom" else (h - ah) // 2
    return blit(canvas(w, h), rows, x, y)


def fill_rect(dst, x0, y0, x1, y1, c):
    for y in range(y0, y1):
        for x in range(x0, x1):
            if 0 <= x < len(dst[0]) and 0 <= y < len(dst):
                dst[y][x] = c
    return dst


def ellipse(dst, cx, cy, rx, ry, c):
    for y in range(len(dst)):
        for x in range(len(dst[0])):
            dx, dy = (x - cx) / max(rx, 0.01), (y - cy) / max(ry, 0.01)
            if dx * dx + dy * dy <= 1.0:
                dst[y][x] = c
    return dst


# ---------------------------------------------------------------------------
# A tiny 3x5 pixel font for signs and banners
# ---------------------------------------------------------------------------

FONT = {
    "A": ".#. #.# ### #.# #.#", "B": "##. #.# ##. #.# ##.",
    "C": ".## #.. #.. #.. .##", "D": "##. #.# #.# #.# ##.",
    "E": "### #.. ##. #.. ###", "F": "### #.. ##. #.. #..",
    "G": ".## #.. #.# #.# .##", "H": "#.# #.# ### #.# #.#",
    "I": "### .#. .#. .#. ###", "J": "..# ..# ..# #.# .#.",
    "K": "#.# #.# ##. #.# #.#", "L": "#.. #.. #.. #.. ###",
    "M": "#.# ### ### #.# #.#", "N": "##. #.# #.# #.# #.#",
    "O": ".#. #.# #.# #.# .#.", "P": "##. #.# ##. #.. #..",
    "Q": ".#. #.# #.# ### .##", "R": "##. #.# ##. #.# #.#",
    "S": ".## #.. .#. ..# ##.", "T": "### .#. .#. .#. .#.",
    "U": "#.# #.# #.# #.# ###", "V": "#.# #.# #.# #.# .#.",
    "W": "#.# #.# ### ### #.#", "X": "#.# #.# .#. #.# #.#",
    "Y": "#.# #.# .#. .#. .#.", "Z": "### ..# .#. #.. ###",
    "0": ".#. #.# #.# #.# .#.", "1": ".#. ##. .#. .#. ###",
    "2": "##. ..# .#. #.. ###", "3": "### ..# .#. ..# ###",
    "4": "#.# #.# ### ..# ..#", "5": "### #.. ##. ..# ##.",
    "6": ".## #.. ### #.# ###", "7": "### ..# .#. .#. .#.",
    "8": "### #.# ### #.# ###", "9": "### #.# ### ..# ##.",
    "(": ".# #. #. #. .#", ")": "#. .# .# .# #.",
    "-": "... ... ### ... ...", "=": "... ### ... ### ...",
    ".": ". . . . #", "!": "# # # . #", ":": ". # . # .",
    "/": "..# ..# .#. #.. #..", " ": ".. .. .. .. ..",
}


def glyph(ch):
    rows = FONT.get(ch.upper(), FONT[" "]).split(" ")
    return [list(r) for r in rows]


def text_width(s, scale=1):
    w = 0
    for ch in s:
        w += (len(glyph(ch)[0]) + 1) * scale
    return w - scale if s else 0


def draw_text(dst, x, y, s, colour, scale=1):
    cx = x
    for ch in s:
        rows = glyph(ch)
        for j, row in enumerate(rows):
            for i, c in enumerate(row):
                if c != "#":
                    continue
                fill_rect(dst, cx + i * scale, y + j * scale,
                          cx + (i + 1) * scale, y + (j + 1) * scale, colour)
        cx += (len(rows[0]) + 1) * scale
    return dst


def sign(w, h, lines, post_h=6, scale=1, board="w", ink="k"):
    """A bordered signboard on two posts, with centred lines of text."""
    dst = canvas(w, h)
    bh = h - post_h
    fill_rect(dst, 0, 0, w, bh, board)
    for x in range(w):
        dst[0][x] = "k"
        dst[bh - 1][x] = "k"
    for y in range(bh):
        dst[y][0] = "k"
        dst[y][w - 1] = "k"
    fill_rect(dst, 3, bh, 6, h, "B")
    fill_rect(dst, w - 6, bh, w - 3, h, "B")
    line_h = 5 * scale + 2
    total = len(lines) * line_h - 2
    y = max(2, (bh - total) // 2)
    for ln in lines:
        draw_text(dst, (w - text_width(ln, scale)) // 2, y, ln, ink, scale)
        y += line_h
    return dst


# ---------------------------------------------------------------------------
# PNG writer (stdlib only)
# ---------------------------------------------------------------------------


def write_png(path, rows):
    h, w = len(rows), len(rows[0])
    raw = bytearray()
    for row in rows:
        raw.append(0)
        for c in row:
            raw.extend(PALETTE.get(c, (0, 0, 0, 0)))

    def chunk(tag, data):
        block = tag + data
        return (struct.pack(">I", len(data)) + block
                + struct.pack(">I", zlib.crc32(block) & 0xFFFFFFFF))

    png = b"\x89PNG\r\n\x1a\n"
    png += chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 6, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(bytes(raw), 9))
    png += chunk(b"IEND", b"")
    with open(path, "wb") as fh:
        fh.write(png)


# ---------------------------------------------------------------------------
# Sprite builders
# ---------------------------------------------------------------------------

BUILDERS = {}


def sprite(sid):
    def register(fn):
        BUILDERS[sid] = fn
        return fn
    return register


# --- the skier -------------------------------------------------------------
# Red cap, teal jacket, navy trousers, black skis, grey poles.

SKIER_DOWN = """
......rrrr......
.....rrrrrr.....
.....rrrrrr.....
......ffff......
.....tttttt.....
....tttttttt....
...d.tttttt.d...
...d.tttttt.d...
...d.tttttt.d...
...d.tttttt.d...
...d..tttt..d...
...d..nnnn..d...
...d..nnnn..d...
......nnnn......
.....nn..nn.....
.....nn..nn.....
.....nn..nn.....
....kk....kk....
....kk....kk....
....kk....kk....
....kk....kk....
....kk....kk....
....kk....kk....
....kk....kk....
....kk....kk....
....kk....kk....
"""


@sprite(1)
def _skier_down():
    return place(SKIER_DOWN, 16, 32)


SKIER_DIAG_R = """
.....rrrr.......
....rrrrrr......
....rrrrrr......
....fffff.......
....tttttt......
...ttttttt.d....
..d.tttttt.d....
..d.tttttt.d....
..d.ttttttd.....
..d.tttttd......
..d..tttt.......
..d..nnnn.......
.....nnnnn......
.....nn.nnn.....
....nn...nn.....
....nn....nn....
...kk.....kk....
...kk......kk...
....kk.....kk...
.....kk.....kk..
.....kk.....kk..
......kk.....kk.
......kk......kk
.......kk.....kk
.......kk......k
........k.......
"""


@sprite(2)
def _skier_diag_r():
    return place(SKIER_DIAG_R, 16, 32)


@sprite(5)
def _skier_diag_l():
    return mirror(place(SKIER_DIAG_R, 16, 32))


SKIER_TRAV_R = """
......rrrr..........
.....rrrrrr.........
.....rrrrrff........
.....tttttff........
....ttttttt.........
...t.tttttt..d......
..dt.tttttt..d......
..d..tttttt..d......
..d..tttttt.d.......
..d...tttt..d.......
..d...nnnn..d.......
..d..nnnnnn.d.......
.....nnnnnn.........
.....nn..nn.........
....nnn..nnn........
....nn....nn........
...knnk...nnk.......
..kkkkkkkkkkkkkkkkkk
.kkkkkkkkkkkkkkkkk..
"""


@sprite(3)
def _skier_trav_r():
    return place(SKIER_TRAV_R, 24, 28)


@sprite(6)
def _skier_trav_l():
    return mirror(place(SKIER_TRAV_R, 24, 28))


SKIER_SIDE_R = """
.......rrrr.........
......rrrrrr........
......rrrrff........
......ttttff........
.....tttttt.........
....d.tttttt.d......
....d.tttttt.d......
....d.tttttt.d......
....d.tttttt.d......
....d..tttt..d......
....d..nnnn..d......
....d.nnnnnn.d......
......nnnnnn........
......nnnnnn........
......nn..nn........
......nn..nn........
.....knnkknnk.......
kkkkkkkkkkkkkkkkkkkk
.kkkkkkkkkkkkkkkkkk.
"""


@sprite(4)
def _skier_side_r():
    return place(SKIER_SIDE_R, 24, 28)


@sprite(7)
def _skier_side_l():
    return mirror(place(SKIER_SIDE_R, 24, 28))


# Side-stepping uphill: same side-on pose with the legs split mid-stride.

SKIER_STEP_L = """
.......rrrr.........
......rrrrrr........
......ffrrrr........
......fftttt........
.....tttttt.........
....d.tttttt.d......
....d.tttttt.d......
....d.tttttt.d......
....d.tttttt.d......
....d..tttt..d......
....d..nnnn..d......
....d.nnnnnn.d......
......nnnnnn........
.....nnn.nnn........
.....nn...nn........
....nnn...nn........
...knnk..knnk.......
kkkkkkkk.kkkkkkkkkk.
..kkkkkkkkkkkkkkkkkk
"""


@sprite(8)
def _skier_step_l():
    return place(SKIER_STEP_L, 24, 28)


@sprite(9)
def _skier_step_r():
    return mirror(place(SKIER_STEP_L, 24, 28))


SKIER_CLIMB_L = """
.......rrrr.........
......rrrrrr........
......ffrrrr........
......fftttt........
.....tttttt.........
....d.tttttt.d......
....d.tttttt.d......
....d.tttttt.d......
....d.tttttt.d......
....d..tttt..d......
....d..nnnn..d......
....d.nnnnnn.d......
......nnnnnn........
......nnnnnn........
......nn..nn........
......nn..nn........
....kknnkknnk.......
.kkkkkkkkkkkkkkkkk..
...kkkkkkkkkkkkkkkk.
"""


@sprite(10)
def _skier_climb_l():
    return place(SKIER_CLIMB_L, 24, 28)


@sprite(11)
def _skier_climb_r():
    return mirror(place(SKIER_CLIMB_L, 24, 28))


# --- crashes ---------------------------------------------------------------


@sprite(12)
def _crash_ouch():
    # A jagged yellow starburst with a red rim and "OUCH!" across it.
    star = """
...............yy..............
....yy.........yy..........yy..
....yyy.......yyyy........yyy...
.....yyy......yyyy.......yyy....
......yyy....yyyyyy.....yyy.....
.......yyyyyyyyyyyyyyyyyyy......
........yyyyyyyyyyyyyyyy........
.....yyyyyyyyyyyyyyyyyyyyy......
...yyyyyyyyyyyyyyyyyyyyyyyyy....
..yyyyyyyyyyyyyyyyyyyyyyyyyy....
.yyyyyyyyyyyyyyyyyyyyyyyyyyyy...
.yyyyyyyyyyyyyyyyyyyyyyyyyyyy...
..yyyyyyyyyyyyyyyyyyyyyyyyyy....
...yyyyyyyyyyyyyyyyyyyyyyyy.....
.....yyyyyyyyyyyyyyyyyyyy.......
.......yyyyyyyyyyyyyyyyyyy......
......yyy....yyyyyy....yyyy.....
.....yyy......yyyy.......yyy....
....yyy.......yyyy........yyy...
....yy.........yy..........yy...
...............yy...............
"""
    dst = place(star, 32, 32, anchor="center")
    dst = remap_rim(dst)
    draw_text(dst, 7, 13, "OUCH!", "k")
    return dst


def remap_rim(dst):
    # Outline the starburst in red so it pops against the snow.
    h, w = len(dst), len(dst[0])
    out = [row[:] for row in dst]
    for y in range(h):
        for x in range(w):
            if dst[y][x] != "y":
                continue
            edge = False
            for dy in (-1, 0, 1):
                for dx in (-1, 0, 1):
                    ny, nx = y + dy, x + dx
                    if not (0 <= ny < h and 0 <= nx < w) or dst[ny][nx] == ".":
                        edge = True
            if edge:
                out[y][x] = "r"
    return out


CRASH_SIT = """
..........rrrr..............
.........rrrrrr.............
.........ffrrrr.............
.........fftttt.............
........tttttt..............
.......tttttttt.............
......tttttttttt............
......tttttttttt.d..........
.......tttttttt..d..........
......nnnnnnnnnn.d..........
.....nnnnnnnnnnnnd..........
..kkk.nnnnnnnnnn.kkk........
kkkkk..www..www..kkkkk......
.kkk....ww..ww....kkk.......
"""


@sprite(13)
def _crash_sit():
    return place(CRASH_SIT, 32, 24)


CRASH_SPRAWL = """
....kk................kk......
.....kk..............kk.......
......kk............kk........
.......kk..........kk.........
........kk...nn...kk..........
.........kknnnnnnkk...........
.......w..nnnnnnnn..w.........
......ww.tttttttttt.ww........
.........tttttttttt...........
......tttttttttttttttt........
.....fftttttttttttttff........
.........rrrr..ww.............
.........rrrrwww..............
"""


@sprite(18)
def _crash_sprawl():
    return place(CRASH_SPRAWL, 32, 26)


CRASH_HEADFIRST = """
........kk........kk........
.........kk......kk.........
..........kk....kk..........
...........kk..kk...........
...........nn..nn...........
...........nn..nn...........
...........nnnnnn...........
..........nnnnnnnn..........
..........tttttttt..........
.........tttttttttt.........
.........tttttttttt.........
..........tttttttt..........
........wwwwwwwwwwww........
......wwwwwwwwwwwwwwww......
....wwwwwwwwwwwwwwwwwwww....
...wwwwwwwwwwwwwwwwwwwwww...
"""


@sprite(19)
def _crash_headfirst():
    return place(CRASH_HEADFIRST, 32, 32)


CRASH_TANGLE = """
......kkkk...........kk......
..........kk......kkkk.......
....kk......kk..kk...........
......kkkk....kkk..kkk.......
..........kk.nnkk.....kk.....
.........nnnnnnnn............
........tttnnnntt............
.......tttttttttt.f..........
......fttttttttttff..........
.......ttttrrrrtt............
........wwrrrrrrww...........
.........wwrrrrww............
"""


@sprite(20)
def _crash_tangle():
    return place(CRASH_TANGLE, 31, 24)


GETTING_UP_L = """
........rrrr.........
.......rrrrrr........
.......ffrrrr........
.......fftttt........
......tttttt.........
.....d.tttttt........
.....d.tttttt........
.....d.tttttt.d......
.....d.tttttt.d......
.....d..tttt..d......
.....d.nnnnnn.d......
.....dnnnnnnnnd......
......nnnnnnnn.......
......nnnnnnnn.......
......nnn..nnn.......
.....knnk..knnk......
kkkkkkkkkkkkkkkkkkk..
..kkkkkkkkkkkkkkkkkk.
"""


@sprite(21)
def _getting_up_l():
    return place(GETTING_UP_L, 25, 31)


@sprite(22)
def _getting_up_r():
    return mirror(place(GETTING_UP_L, 25, 31))


# --- airborne and tricks ---------------------------------------------------

JUMP_LOW = """
.........rrrr...........
........rrrrrr..........
........rrrrrr..........
.........ffff...........
....d...tttttt...d......
.....d.tttttttt.d.......
.....d.tttttttt.d.......
......dtttttttd.........
.......tttttt...........
.......nnnnnn...........
......nnnnnnnn..........
......nnn..nnn..........
.....knnk..knnk.........
..kkkkkkkkkkkkkkkkkk....
.kkkkkkkkkkkkkkkkkk.....
"""


@sprite(14)
def _jump_low():
    return place(JUMP_LOW, 32, 32, anchor="center")


JUMP_HIGH_L = """
d.....................d.....
.d...................d......
..d.....rrrr........d.......
...d...rrrrrr......d........
....d..rrrrff.....d.........
.....d.ttttff....d..........
......tttttttttt............
.....ttttttttttt............
....tttttttttttt............
.......tttttt...............
.......nnnnnn...............
......nnnnnnnn..............
.....nnn...nnn..............
....knnk...knnk.............
.kkkkkkkk.kkkkkkkkk.........
kkkkkkk..kkkkkkkkkkk........
"""


@sprite(15)
def _jump_high_l():
    return place(JUMP_HIGH_L, 28, 31, anchor="center")


@sprite(16)
def _jump_high_r():
    return mirror(place(JUMP_HIGH_L, 28, 31, anchor="center"))


JUMP_TUCK = """
......kkkkkkkkkkkkkk........
....kkkkkkkkkkkkkkkkkk......
...kknnk..........knnk......
.....nnn..........nnn.......
.....nnnnnn....nnnnnn.......
......nnnnnnnnnnnnn.........
.......tttttttttttt.........
......tttttttttttttt........
.....fttttttttttttttf.......
......tttttttttttttt........
........tttttttt............
.........rrrrrr.............
.........rrrrrr.............
..........ffff..............
"""


@sprite(17)
def _jump_tuck():
    return place(JUMP_TUCK, 28, 34, anchor="center")


# --- slalom flags and gate markers ----------------------------------------


@sprite(23)
def _flag_left():
    art = """
rrrrrrr.....
rrrrrrrk....
.rrrrrkk....
..rrrkkk....
....kkk.....
.....kk.....
.....kk.....
.....kk.....
.....kk.....
.....kk.....
.....kk.....
.....kk.....
.....kk.....
.....kk.....
....dkkd....
"""
    return place(art, 12, 24)


@sprite(24)
def _flag_right():
    return mirror(_flag_left())


def gate_face(colour, happy):
    dst = canvas(12, 24)
    fill_rect(dst, 5, 10, 7, 24, "d")
    ellipse(dst, 5.5, 5.5, 5.4, 5.4, colour)
    dst[4][3] = dst[4][8] = "k"
    if happy:
        for x, y in ((3, 7), (4, 8), (5, 8), (6, 8), (7, 8), (8, 7)):
            dst[y][x] = "k"
    else:
        for x, y in ((3, 8), (4, 7), (5, 7), (6, 7), (7, 7), (8, 8)):
            dst[y][x] = "k"
    return dst


@sprite(25)
def _gate_green():
    return gate_face("e", True)


@sprite(26)
def _gate_red():
    return gate_face("r", False)


# --- scenery ---------------------------------------------------------------


@sprite(27)
def _cloud():
    dst = canvas(64, 32)
    for cx, cy, rx, ry in ((18, 20, 14, 8), (34, 14, 15, 9),
                           (48, 20, 13, 8), (32, 22, 22, 8)):
        ellipse(dst, cx, cy, rx, ry, "s")
    for cx, cy, rx, ry in ((18, 18, 11, 6), (34, 13, 12, 7),
                           (47, 18, 10, 6), (32, 20, 19, 6)):
        ellipse(dst, cx, cy, rx, ry, "w")
    return dst


TREE = """
.............ww.............
............wEEw............
............EEEE............
...........wEEEEw...........
...........EEEEEE...........
..........eEEEEEEw..........
..........eeEEEEEE..........
.........eeeEEEEEEw.........
.........eeeeEEEEEE.........
........eeeeeEEEEEEE........
.........eeeeEEEEEE.........
..........eeeEEEEE..........
.........eeeeEEEEEE.........
........eeeeeEEEEEEE........
.......eeeeeeEEEEEEEE.......
......eeeeeeeEEEEEEEEE......
........eeeeeEEEEEEE........
.......eeeeeeEEEEEEEE.......
......eeeeeeeEEEEEEEEE......
.....eeeeeeeeEEEEEEEEEE.....
....eeeeeeeeeEEEEEEEEEEE....
...eeeeeeeeeeEEEEEEEEEEEE...
..eeeeeeeeeeeEEEEEEEEEEEEE..
............BBBB............
............BBBB............
...........BBBBBB...........
"""


@sprite(49)
def _tree():
    return place(TREE, 28, 32)


TREE_BARE = """
.....B.........B......
......B..B....B.......
..B....B.B...B........
...B...BBB..B...B.....
....B..BB..BB..B......
.....BBBBB.B..B.......
.......BBBBB.B........
....BBBBBBBBB.........
.......BBBB...........
........BBB...........
........BBB...........
........BBB...........
.......BBBB...........
.......BBBBB..........
"""


@sprite(50)
def _tree_bare():
    return place(TREE_BARE, 22, 27)


TREE_BIG = """
...............ww...............
..............wEEw..............
..............EEEE..............
.............wEEEEw.............
.............EEEEEE.............
............eEEEEEEw............
............eeEEEEEE............
...........eeeEEEEEEw...........
...........eeeEEEEEEE...........
..........eeeeEEEEEEEE..........
...........eeeEEEEEEE...........
..........eeeeEEEEEEEE..........
..........eeeeEEEEEEEE..........
.........eeeeeEEEEEEEEE.........
.........eeeeeEEEEEEEEE.........
........eeeeeeEEEEEEEEEE........
........eeeeeeEEEEEEEEEE........
.......eeeeeeeEEEEEEEEEEE.......
..........eeeeEEEEEEEE..........
.........eeeeeEEEEEEEEE.........
.........eeeeeEEEEEEEEE.........
........eeeeeeEEEEEEEEEE........
........eeeeeeEEEEEEEEEE........
.......eeeeeeeEEEEEEEEEEE.......
.......eeeeeeeEEEEEEEEEEE.......
......eeeeeeeeEEEEEEEEEEEE......
......eeeeeeeeEEEEEEEEEEEE......
.....eeeeeeeeeEEEEEEEEEEEEE.....
.....eeeeeeeeeEEEEEEEEEEEEE.....
....eeeeeeeeeeEEEEEEEEEEEEEE....
....eeeeeeeeeeEEEEEEEEEEEEEE....
...eeeeeeeeeeeEEEEEEEEEEEEEEE...
...eeeeeeeeeeeEEEEEEEEEEEEEEE...
..eeeeeeeeeeeeEEEEEEEEEEEEEEEE..
..eeeeeeeeeeeeEEEEEEEEEEEEEEEE..
.eeeeeeeeeeeeeEEEEEEEEEEEEEEEEE.
eeeeeeeeeeeeeeEEEEEEEEEEEEEEEEEE
.............BBBBBB.............
.............BBBBBB.............
.............BBBBBB.............
.............BBBBBB.............
............BBBBBBBB............
"""


@sprite(51)
def _tree_big():
    return place(TREE_BIG, 32, 64)


def xmas_tree(a, b, c):
    art = remap(grid(TREE), {})
    dst = place(art, 28, 32)
    for x, y, ch in ((9, 10, a), (17, 13, b), (12, 16, c), (19, 19, a),
                     (7, 20, b), (14, 21, c), (13, 1, "y")):
        if dst[y][x] != ".":
            dst[y][x] = ch
            if dst[y][x + 1] != ".":
                dst[y][x + 1] = ch
    return dst


@sprite(87)
def _xmas_a():
    return xmas_tree("r", "y", "b")


@sprite(88)
def _xmas_b():
    return xmas_tree("y", "b", "r")


@sprite(89)
def _xmas_c():
    return xmas_tree("b", "r", "y")


TREE_BURNT = """
.....d.........d......
......d..d....d.......
..d....d.d...d........
...d...ddd..d...d.....
....d..dd..dd..d......
.....ddddd.d..d.......
.......ddddd.d........
....ddddddddd.........
.......dddd...........
........kkk...........
....r...kkk...........
...rr...kkk.r.........
.......kkkk.rr........
.......kkkkk..........
"""


@sprite(83)
def _burnt_a():
    return place(TREE_BURNT, 22, 27)


@sprite(84)
def _burnt_b():
    return mirror(place(TREE_BURNT, 22, 27))


@sprite(85)
def _burnt_c():
    return place(remap(grid(TREE_BURNT), {"r": "o"}), 22, 27)


ROCK = """
........ssssss.........
.....sssswwwsss........
....sswwwwssssss.......
...sswwwsssssssgg......
..ssssssssssggggg......
..sssssssgggggggg......
.ssssssgggggggggg......
.sssggggggggggggdd.....
.ggggggggggggdddd......
..gggggggddddddd.......
"""


@sprite(45)
def _rock():
    return place(ROCK, 23, 11)


STUMP = """
....BBBBBBB.....
..BBBLLLLLBB....
.BBLLwwLLLLBB...
.BBLwLLwLLLBB...
.BBLLwwLLLLBB...
..BBLLLLLLBB....
..BBBBBBBBBB....
..BBBBBBBBBB....
..BBBBBBBBBBB...
"""


@sprite(46)
def _stump():
    return place(STUMP, 16, 11)


@sprite(47)
def _mogul_small():
    art = """
....ssssssss....
..sswwwwwwwwss..
.swwwwwwwwwwws..
sssssssssssssss.
"""
    return place(art, 16, 4)


@sprite(48)
def _mogul_large():
    art = """
........ssssssss........
.....ssswwwwwwwwsss.....
...sswwwwwwwwwwwwwwss...
..swwwwwwwwwwwwwwwwwws..
.swwwwwwwwwwwwwwwwwwwws.
sssssssssssssssssssssss.
"""
    return place(art, 24, 8)


@sprite(52)
def _ramp():
    art = """
............rrrrrrrr............
........rrrrppppppppbbbb........
......bbppbbbbbbbbbbbbeeee......
....eebbeeeeeeeeeeeeeeeeyyyy....
..yyeeyyyyyyyyyyyyyyyyyyyyoooo..
.ooyyooooooooooooooooooooooooor.
.wwwwwwwwwwwwwwwwwwwwwwwwwwwww.
sssssssssssssssssssssssssssssss.
"""
    return place(art, 32, 8)


@sprite(82)
def _snow_patch():
    art = """
....LLLLLLL.....
..LLLBBLLLLLL...
.LLBBBBBLLBBLL..
..LLLBBBBBBLL...
....LLLLLLL.....
"""
    return place(art, 16, 8)


# --- chairlift -------------------------------------------------------------


@sprite(64)
def _lift_tower():
    dst = canvas(24, 64)
    fill_rect(dst, 0, 2, 24, 4, "d")           # crossarm
    fill_rect(dst, 2, 0, 4, 6, "g")            # sheave stacks
    fill_rect(dst, 20, 0, 22, 6, "g")
    for y in range(4, 60):                      # lattice mast
        dst[y][10] = dst[y][13] = "g"
        if y % 4 == 0:
            dst[y][11] = dst[y][12] = "s"
        if y % 4 == 2:
            dst[y][11] = dst[y][12] = "g"
    fill_rect(dst, 6, 60, 18, 64, "d")          # footing
    return dst


def chair(riders):
    dst = canvas(26, 32)
    fill_rect(dst, 0, 0, 26, 1, "d")            # cable
    fill_rect(dst, 12, 1, 14, 10, "g")          # hanger
    fill_rect(dst, 4, 10, 22, 12, "d")          # seat back rail
    fill_rect(dst, 4, 10, 6, 22, "d")
    fill_rect(dst, 4, 20, 24, 22, "d")          # seat
    fill_rect(dst, 22, 22, 24, 26, "d")         # footrest drop
    if riders >= 1:
        blit(dst, grid("""
.oo.
oooo
oooo
.bb.
.bb.
"""), 7, 12)
        fill_rect(dst, 7, 22, 9, 26, "b")
    if riders >= 2:
        blit(dst, grid("""
.pp.
pppp
pppp
.nn.
.nn.
"""), 15, 12)
        fill_rect(dst, 15, 22, 17, 26, "n")
    return dst


@sprite(65)
def _chair_full():
    return chair(1)


@sprite(66)
def _chair_pair():
    return chair(2)


@sprite(67)
def _chair_empty():
    return chair(0)


# --- other skiers ----------------------------------------------------------
# The rival skier wears orange and blue; the boarder purple with a yellow board.

SKIER2_DOWN = """
......yyyy......
.....yyyyyy.....
......ffff......
.....oooooo.....
....oooooooo....
...d.oooooo.d...
...d.oooooo.d...
...d.oooooo.d...
...d..oooo..d...
...d..bbbb..d...
......bbbb......
.....bb..bb.....
.....bb..bb.....
....kk....kk....
....kk....kk....
....kk....kk....
....kk....kk....
....kk....kk....
....kk....kk....
....kk....kk....
"""


@sprite(28)
def _skier2_down():
    return place(SKIER2_DOWN, 24, 30)


SKIER2_DIAG_L = """
......yyyy......
.....yyyyyy.....
......ffff......
.....oooooo.....
....oooooooo....
..d.oooooo.d....
..d.oooooo.d....
..d.oooooo.d....
..d..oooo..d....
.....bbbb.......
....bbbbb.......
....bb.bb.......
...bb..bb.......
...kk...kk......
..kk....kk......
..kk...kk.......
.kk....kk.......
.kk...kk........
kk....kk........
kk...kk.........
"""


@sprite(29)
def _skier2_diag_l():
    return place(SKIER2_DIAG_L, 22, 29)


@sprite(30)
def _skier2_diag_r():
    return place(mirror(grid(SKIER2_DIAG_L)), 21, 29)


SKIER2_CRASH = """
........yyyy...........
.......yyyyyy..........
.......ffyyyy..........
.......oooooo..........
......oooooooo.........
.....oooooooooo........
......oooooooo.........
.....bbbbbbbbbb.d......
....bbbbbbbbbbbbd......
..kkk.bbbbbbbb.kkk.....
.kkkk..ww..ww..kkkk....
..kk...ww..ww...kk.....
"""


@sprite(31)
def _skier2_crash():
    return place(SKIER2_CRASH, 24, 24)


SKIER2_SPRAWL = """
..kk..............kk....
...kk............kk.....
....kk..........kk......
.....kk...bb...kk.......
......kkbbbbbbkk........
.....w..bbbbbb..w.......
....ww.oooooooo.ww......
.......oooooooo.........
.....oooooooooooo.......
....ffoooooooooof.......
........yyyy.ww.........
........yyyyww..........
"""


@sprite(32)
def _skier2_sprawl():
    return place(SKIER2_SPRAWL, 24, 24)


# --- the dog ---------------------------------------------------------------

DOG_A = """
..................BB.
.............B...BBB.
..BB.........BB.BBB..
.BBBB.......BBBBBB...
..BBBBBBBBBBBBBB.....
...BBBBBBBBBBBB......
...BB..BBB...BB......
..BB..BB......BB.....
..B..BB........B.....
"""

DOG_B = """
..................BB.
.............B...BBB.
..BB.........BB.BBB..
.BBBB.......BBBBBB...
..BBBBBBBBBBBBBB.....
...BBBBBBBBBBBB......
....BBB...BBB........
...BB.......BB.......
....BB.......BB......
"""


@sprite(33)
def _dog_a():
    return place(DOG_A, 21, 15)


@sprite(34)
def _dog_b():
    return place(DOG_B, 21, 15)


DOG_BARK = """
..w..w.........
.w..w..........
..w...BB.......
......BBB..w...
....BBBBB.w....
...BBBBBB......
..BBBBBBB......
...BBBBBBB.....
...BB...BBB....
...BB....BBB...
..BBB.....BB...
"""


@sprite(35)
def _dog_bark_a():
    return place(DOG_BARK, 19, 19)


@sprite(36)
def _dog_bark_b():
    art = remap(grid(DOG_BARK), {"w": "s"})
    return place(shift_up(art, 1), 19, 19)


# --- snowboarders ----------------------------------------------------------


def boarder(w, h, lean):
    """A purple-suited boarder on a yellow board, leaning -1/0/+1."""
    dst = canvas(w, h)
    cx = w // 2
    fill_rect(dst, max(0, cx - 8 + lean * 3), h - 3,
              min(w, cx + 8 + lean * 3), h - 1, "y")   # board
    fill_rect(dst, cx - 2, h - 7, cx + 2, h - 3, "n")  # legs
    fill_rect(dst, cx - 3 + lean, h - 13, cx + 3 + lean, h - 7, "p")
    fill_rect(dst, cx - 5 + lean, h - 11, cx + 5 + lean, h - 9, "p")  # arms
    fill_rect(dst, cx - 2 + lean, h - 16, cx + 2 + lean, h - 13, "f")
    fill_rect(dst, cx - 2 + lean, h - 18, cx + 2 + lean, h - 15, "e")  # cap
    return dst


@sprite(37)
def _boarder_a():
    return boarder(26, 30, -1)


@sprite(38)
def _boarder_b():
    return boarder(20, 30, 0)


@sprite(39)
def _boarder_c():
    return boarder(25, 31, 1)


@sprite(40)
def _boarder_d():
    dst = boarder(30, 29, 0)
    fill_rect(dst, 2, 20, 8, 22, "y")   # board grabbed sideways
    return dst


def boarder_crash(w, h, flip):
    dst = canvas(w, h)
    cx, cy = w // 2, h - 8
    fill_rect(dst, cx - 8, cy + 4, cx + 8, cy + 6, "w")      # snow spray
    fill_rect(dst, cx - 4, cy - 2, cx + 4, cy + 4, "p")      # heap
    fill_rect(dst, cx - 6, cy, cx - 2, cy + 2, "f")
    if flip:
        fill_rect(dst, cx - 10, cy - 6, cx + 2, cy - 4, "y")  # board up
    else:
        fill_rect(dst, cx - 2, cy - 6, cx + 10, cy - 4, "y")
    fill_rect(dst, cx + 2, cy - 3, cx + 5, cy - 1, "e")
    return dst


@sprite(41)
def _boarder_crash_a():
    return boarder_crash(32, 32, False)


@sprite(42)
def _boarder_crash_b():
    return boarder_crash(32, 32, True)


@sprite(43)
def _boarder_crash_c():
    return boarder_crash(25, 29, False)


@sprite(44)
def _boarder_crash_d():
    return boarder_crash(29, 25, True)


# --- signage ---------------------------------------------------------------


def peak(dst, apex_x, apex_y, height, cap=5):
    """A snow-capped mountain: grey triangle, white for the top `cap` rows."""
    for j in range(height):
        colour = "w" if j < cap else "g"
        blit(dst, [[colour] * (2 * j + 1)], apex_x - j, apex_y + j)


@sprite(53)
def _logo():
    dst = canvas(93, 57)
    peak(dst, 31, 1, 16)
    peak(dst, 59, 4, 13)
    draw_text(dst, (93 - text_width("OMARSKI", 3)) // 2, 20, "OMARSKI", "n", 3)
    draw_text(dst, (93 - text_width("A FREE OMARCHY GAME", 1)) // 2, 40,
              "A FREE OMARCHY GAME", "k", 1)
    draw_text(dst, (93 - text_width("SKI FAST. AVOID THE YETI.", 1)) // 2, 50,
              "SKI FAST. AVOID THE YETI.", "d", 1)
    return dst


@sprite(54)
def _version():
    dst = canvas(52, 10)
    draw_text(dst, 0, 2, "VERSION 2.0", "k")
    return dst


@sprite(55)
def _hint_numpad():
    dst = canvas(92, 30)
    draw_text(dst, (92 - text_width("USE NUMPAD (0-9)", 1)) // 2, 6,
              "USE NUMPAD (0-9)", "k")
    draw_text(dst, (92 - text_width("FOR BETTER CONTROL", 1)) // 2, 16,
              "FOR BETTER CONTROL", "k")
    return dst


@sprite(56)
def _hint_keys():
    dst = canvas(63, 32)
    draw_text(dst, (63 - text_width("F2 = RESTART", 1)) // 2, 4,
              "F2 = RESTART", "k")
    draw_text(dst, (63 - text_width("F3 = PAUSE", 1)) // 2, 13,
              "F3 = PAUSE", "k")
    draw_text(dst, (63 - text_width("F = FAST", 1)) // 2, 22, "F = FAST", "k")
    return dst


@sprite(57)
def _sign_start_r():
    dst = canvas(42, 27)
    # A pennant post marking the right edge of the start line.
    fill_rect(dst, 30, 4, 32, 27, "B")
    blit(dst, grid("""
eeeeeeeeee
eeeeeeeek.
.eeeeeek..
..eeeek...
....ek....
"""), 32, 4)
    blit(dst, sign(28, 18, ["GO!"], post_h=5, scale=2), 0, 9)
    return dst


@sprite(58)
def _sign_start_l():
    return blit(canvas(42, 27), sign(40, 27, ["START"], post_h=6, scale=2), 0, 0)


@sprite(59)
def _sign_finish_r():
    dst = canvas(50, 29)
    fill_rect(dst, 38, 2, 40, 29, "B")
    # Checkered flag.
    for j in range(8):
        for i in range(10):
            dst[2 + j][40 + i] = "k" if (i // 2 + j // 2) % 2 == 0 else "w"
    blit(dst, sign(36, 20, ["WELL", "DONE"], post_h=5, scale=1), 0, 9)
    return dst


@sprite(60)
def _sign_finish_l():
    return blit(canvas(50, 29), sign(48, 29, ["FINISH"], post_h=6, scale=2), 0, 0)


@sprite(61)
def _sign_slalom():
    return sign(40, 36, ["SLALOM"], post_h=8, scale=1)


@sprite(62)
def _sign_tree_slalom():
    return sign(44, 36, ["TREE", "SLALOM"], post_h=8, scale=1)


@sprite(63)
def _sign_freestyle():
    return sign(40, 35, ["FREE", "STYLE"], post_h=8, scale=1)


# --- the yeti --------------------------------------------------------------
# A shaggy grey-white monster with a lolling pink mouth. Outlined in dark
# grey so he reads against the snow.

YETI_ROAR = """
..dd......................dd....
.dssd....................dssd...
.dssd......dddddddd......dssd...
.dssd.....dssssssssd.....dssd...
.dssd....dsswsswssssd....dssd...
.dsssd...dswkswwkwssd...dsssd...
..dssd...dsswsswssssd...dssd....
..dssd...dssssssssssd...dssd....
..dsssd..dsmmmmmmmssd..dsssd....
..dsssd..dsmwmwmwmssd..dsssd....
...dsssd.dssmmmmmsssd.dsssd.....
...dsssddssssssssssssddsssd.....
....dsssdssswwssswsssdsssd......
....dssssssswwssswssssssd.......
.....dsssssssssssssssssd........
......dsssssswwwsssssssd........
......dssssswwwwwssssssd........
......dsssswwwwwwwsssssd........
......dsssswwwwwwwsssssd........
......dsssswwwwwwwsssssd........
......dsssswwwwwwwsssssd........
......dssssswwwwwssssssd........
......dssssssssssssssssd........
.......dssssssssssssssd.........
.......dssssdssssdssssd.........
.......dsssd..dd..dsssd.........
.......dsssd......dsssd.........
......dsssd........dsssd........
......dsssd........dsssd........
......dsssd........dsssd........
.....dssssd........dssssd.......
.....dssssd........dssssd.......
....ddssssdd......ddssssdd......
....dssssssd......dssssssd......
....dddddddd......dddddddd......
"""


@sprite(68)
def _yeti_roar_a():
    return place(YETI_ROAR, 32, 48)


@sprite(69)
def _yeti_roar_b():
    return place(shift_up(grid(YETI_ROAR), 2), 32, 48)


YETI_RUN_A = """
...........dddddddd.............
..........dsssssssssd...........
.........dsswsswssssd...........
.........dswkswwkwssd...........
.........dsswsswssssd...........
.........dssssssssssd...........
.........dssmmmmmsssd...........
..dd......dssssssssd......dd....
.dssd....dssssssssssd....dssd...
.dssdddddsssswwsswsssdddddssd...
.dssssssssssswwsswssssssssssd...
..dsssssssssssssssssssssssd.....
....ddssssssswwwwwssssdd........
.......dsssswwwwwwwsssd.........
.......dssswwwwwwwwwssd.........
.......dssswwwwwwwwwssd.........
.......dssswwwwwwwwwssd.........
.......dsssswwwwwwwssd..........
.......dssssssssssssd...........
......dssssssssssssd............
......dsssdssssssdssd...........
.....dsssd..dsssssssd...........
....dsssd....dssssd.............
...dsssd......dssssd............
..dsssd........dssssd...........
..dsssd.........dssssd..........
.dsssd...........dssssd.........
.dsssd............dssssdd.......
.dsssdd............dssssssd.....
..dssssd............ddddddd.....
...ddddd........................
"""

YETI_RUN_B = """
...........dddddddd.............
..........dsssssssssd...........
.........dsswsswssssd...........
.........dswkswwkwssd...........
.........dsswsswssssd...........
.........dssssssssssd...........
.........dssmmmmmsssd...........
..dd......dssssssssd......dd....
.dssd....dssssssssssd....dssd...
.dssdddddsssswwsswsssdddddssd...
.dssssssssssswwsswssssssssssd...
..dsssssssssssssssssssssssd.....
....ddssssssswwwwwssssdd........
.......dsssswwwwwwwsssd.........
.......dssswwwwwwwwwssd.........
.......dssswwwwwwwwwssd.........
.......dssswwwwwwwwwssd.........
.......dsssswwwwwwwssd..........
.......dssssssssssssd...........
......dssssssssssssd............
......dssdssssssdsssd...........
......dssssssd..dsssd...........
.....dssssd......dsssd..........
....dssssd........dsssd.........
...dssssd..........dsssd........
..dssssd............dsssd.......
.dssssd.............dsssd.......
dssssd...............dsssdd.....
dsssd.................dssssd....
dsssdd.................ddddd....
.ddddd..........................
"""


@sprite(70)
def _yeti_run_a():
    return place(YETI_RUN_A, 32, 48)


@sprite(71)
def _yeti_run_b():
    return place(YETI_RUN_B, 32, 48)


@sprite(72)
def _yeti_run_c():
    return place(shift_up(grid(YETI_RUN_A), 2), 32, 48)


@sprite(73)
def _yeti_run_d():
    return place(shift_up(grid(YETI_RUN_B), 2), 32, 48)


YETI_LEAP = """
.....ddddddddd..................
....dsssssssssd.....dd..........
...dsswsswsssssd...dssd.........
...dswkswwkwsssd..dssd..........
...dsswsswsssssd.dssd...........
...dssmmmmmmsssddssd............
...dssmwmwmwsssdssd.............
...dssmmmmmmssssssd.............
....dsssssssssssssd.............
..dddsssswwsswssssdd............
.dssssssswwsswsssssssd..........
.dsssssssssssssssssssssd........
..ddsssswwwwwwwsssssssssd.......
....dsswwwwwwwwwssssssssd.......
....dsswwwwwwwwwsssdssssd.......
....dsswwwwwwwwwssd.dsssd.......
....dssswwwwwwwssd...dsssd......
....dsssssssssssd.....dsssd.....
...dsssssssssssd.......dsssd....
...dssssdsssssd.........dssd....
..dsssd..dssssd..........dssd...
.dsssd....dssssd.........dssdd..
dsssd......dssssd........dssssd.
dssd........ddddd.........ddddd.
"""


@sprite(74)
def _yeti_leap_a():
    return place(YETI_LEAP, 32, 48)


@sprite(75)
def _yeti_leap_b():
    return place(shift_up(grid(YETI_LEAP), 2), 32, 48)


def yeti_body():
    """Standing yeti with a big mouth area, used by the eating frames."""
    return grid("""
...........dddddddd.............
..........dsssssssssd...........
.........dsswsswssssd...........
.........dswkswwkwssd...........
.........dsswsswssssd...........
.........dssssssssssd...........
.........dsmmmmmmmssd...........
.........dsmmmmmmmssd...........
.........dssmmmmmsssd...........
........ddssssssssssdd..........
.......dssssswwsswssssd.........
......dsssssswwsswsssssd........
......dsssssssssssssssd.........
......dsssssswwwsssssssd........
......dssssswwwwwssssssd........
......dsssswwwwwwwsssssd........
......dsssswwwwwwwsssssd........
......dsssswwwwwwwsssssd........
......dssssswwwwwssssssd........
......dssssssssssssssssd........
.......dssssssssssssssd.........
.......dssssdssssdssssd.........
.......dsssd..dd..dsssd.........
......dsssd........dsssd........
......dsssd........dsssd........
.....dssssd........dssssd.......
....ddssssdd......ddssssdd......
....dssssssd......dssssssd......
....dddddddd......dddddddd......
""")


@sprite(76)
def _yeti_eat_a():
    # Skier held aloft in one raised arm.
    dst = place(yeti_body(), 32, 48)
    fill_rect(dst, 24, 10, 27, 20, "s")
    blit(dst, grid("""
.rr.
.ff.
tttt
tttt
.nn.
kkkk
"""), 24, 2)
    return dst


@sprite(77)
def _yeti_eat_b():
    # Skier lowered to the mouth.
    dst = place(yeti_body(), 32, 48)
    blit(dst, grid("""
.rr.
tttt
.nn.
"""), 17, 16)
    return dst


@sprite(78)
def _yeti_eat_c():
    # Legs sticking out of the jaws.
    dst = place(yeti_body(), 32, 48)
    blit(dst, grid("""
nn.nn
nn.nn
kk.kk
"""), 13, 19)
    return dst


@sprite(79)
def _yeti_eat_d():
    # Swallowed: a bulge and a spare ski.
    dst = place(yeti_body(), 32, 48)
    fill_rect(dst, 12, 32, 20, 36, "s")
    blit(dst, grid("kkkkkk"), 22, 40)
    return dst


@sprite(80)
def _yeti_chew():
    dst = place(yeti_body(), 32, 48)
    # Mouth shut, contented: overwrite the maw with fur and a thin smile.
    fill_rect(dst, 11, 19, 20, 22, "s")
    fill_rect(dst, 12, 20, 19, 21, "d")
    return dst


@sprite(81)
def _yeti_burp():
    dst = place(yeti_body(), 32, 48)
    # Wide-open mouth and a flung ski.
    fill_rect(dst, 11, 18, 20, 23, "m")
    fill_rect(dst, 13, 20, 18, 22, "R")
    blit(dst, grid("""
....kk
...kk.
..kk..
.kk...
kk....
"""), 25, 4)
    return dst


@sprite(86)
def _ski_scrap():
    art = """
k....k..
.k...k..
.k..k...
..k.k...
..k.k...
..kk....
..kk....
.k..k...
.k...k..
k....kk.
"""
    return place(art, 8, 11)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def build(outdir):
    os.makedirs(outdir, exist_ok=True)
    for sid in sorted(SIZES):
        if sid not in BUILDERS:
            raise SystemExit("no builder for sprite %d" % sid)
        rows = BUILDERS[sid]()
        w, h = SIZES[sid]
        if len(rows[0]) != w or len(rows) != h:
            raise SystemExit("sprite %d is %dx%d, expected %dx%d"
                             % (sid, len(rows[0]), len(rows), w, h))
        write_png(os.path.join(outdir, "%03d.png" % sid), rows)
    print("wrote %d sprites to %s" % (len(SIZES), outdir))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    default_out = os.path.join(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))), "assets", "sprites")
    parser.add_argument("-o", "--outdir", default=default_out)
    args = parser.parse_args()
    build(args.outdir)


if __name__ == "__main__":
    main()
